//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_05_24ULSAVentas.ServicioLocal {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioLocal.ServicioExamenSoap")]
    public interface ServicioExamenSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento DevolverCadenaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DevolverCadena", ReplyAction="*")]
        _2017_05_24ULSAVentas.ServicioLocal.DevolverCadenaResponse DevolverCadena(_2017_05_24ULSAVentas.ServicioLocal.DevolverCadenaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DevolverCadena", ReplyAction="*")]
        System.Threading.Tasks.Task<_2017_05_24ULSAVentas.ServicioLocal.DevolverCadenaResponse> DevolverCadenaAsync(_2017_05_24ULSAVentas.ServicioLocal.DevolverCadenaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/calcularTotal", ReplyAction="*")]
        double calcularTotal(int idPublicacion, int cantidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/calcularTotal", ReplyAction="*")]
        System.Threading.Tasks.Task<double> calcularTotalAsync(int idPublicacion, int cantidad);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento coincidencia del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listaModelo", ReplyAction="*")]
        _2017_05_24ULSAVentas.ServicioLocal.listaModeloResponse listaModelo(_2017_05_24ULSAVentas.ServicioLocal.listaModeloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listaModelo", ReplyAction="*")]
        System.Threading.Tasks.Task<_2017_05_24ULSAVentas.ServicioLocal.listaModeloResponse> listaModeloAsync(_2017_05_24ULSAVentas.ServicioLocal.listaModeloRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DevolverCadenaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DevolverCadena", Namespace="http://tempuri.org/", Order=0)]
        public _2017_05_24ULSAVentas.ServicioLocal.DevolverCadenaRequestBody Body;
        
        public DevolverCadenaRequest() {
        }
        
        public DevolverCadenaRequest(_2017_05_24ULSAVentas.ServicioLocal.DevolverCadenaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DevolverCadenaRequestBody {
        
        public DevolverCadenaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DevolverCadenaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DevolverCadenaResponse", Namespace="http://tempuri.org/", Order=0)]
        public _2017_05_24ULSAVentas.ServicioLocal.DevolverCadenaResponseBody Body;
        
        public DevolverCadenaResponse() {
        }
        
        public DevolverCadenaResponse(_2017_05_24ULSAVentas.ServicioLocal.DevolverCadenaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DevolverCadenaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DevolverCadenaResult;
        
        public DevolverCadenaResponseBody() {
        }
        
        public DevolverCadenaResponseBody(string DevolverCadenaResult) {
            this.DevolverCadenaResult = DevolverCadenaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listaModeloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listaModelo", Namespace="http://tempuri.org/", Order=0)]
        public _2017_05_24ULSAVentas.ServicioLocal.listaModeloRequestBody Body;
        
        public listaModeloRequest() {
        }
        
        public listaModeloRequest(_2017_05_24ULSAVentas.ServicioLocal.listaModeloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class listaModeloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string coincidencia;
        
        public listaModeloRequestBody() {
        }
        
        public listaModeloRequestBody(string coincidencia) {
            this.coincidencia = coincidencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listaModeloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listaModeloResponse", Namespace="http://tempuri.org/", Order=0)]
        public _2017_05_24ULSAVentas.ServicioLocal.listaModeloResponseBody Body;
        
        public listaModeloResponse() {
        }
        
        public listaModeloResponse(_2017_05_24ULSAVentas.ServicioLocal.listaModeloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class listaModeloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public _2017_05_24ULSAVentas.ServicioLocal.ArrayOfString listaModeloResult;
        
        public listaModeloResponseBody() {
        }
        
        public listaModeloResponseBody(_2017_05_24ULSAVentas.ServicioLocal.ArrayOfString listaModeloResult) {
            this.listaModeloResult = listaModeloResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioExamenSoapChannel : _2017_05_24ULSAVentas.ServicioLocal.ServicioExamenSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioExamenSoapClient : System.ServiceModel.ClientBase<_2017_05_24ULSAVentas.ServicioLocal.ServicioExamenSoap>, _2017_05_24ULSAVentas.ServicioLocal.ServicioExamenSoap {
        
        public ServicioExamenSoapClient() {
        }
        
        public ServicioExamenSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioExamenSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioExamenSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioExamenSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _2017_05_24ULSAVentas.ServicioLocal.DevolverCadenaResponse _2017_05_24ULSAVentas.ServicioLocal.ServicioExamenSoap.DevolverCadena(_2017_05_24ULSAVentas.ServicioLocal.DevolverCadenaRequest request) {
            return base.Channel.DevolverCadena(request);
        }
        
        public string DevolverCadena() {
            _2017_05_24ULSAVentas.ServicioLocal.DevolverCadenaRequest inValue = new _2017_05_24ULSAVentas.ServicioLocal.DevolverCadenaRequest();
            inValue.Body = new _2017_05_24ULSAVentas.ServicioLocal.DevolverCadenaRequestBody();
            _2017_05_24ULSAVentas.ServicioLocal.DevolverCadenaResponse retVal = ((_2017_05_24ULSAVentas.ServicioLocal.ServicioExamenSoap)(this)).DevolverCadena(inValue);
            return retVal.Body.DevolverCadenaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_2017_05_24ULSAVentas.ServicioLocal.DevolverCadenaResponse> _2017_05_24ULSAVentas.ServicioLocal.ServicioExamenSoap.DevolverCadenaAsync(_2017_05_24ULSAVentas.ServicioLocal.DevolverCadenaRequest request) {
            return base.Channel.DevolverCadenaAsync(request);
        }
        
        public System.Threading.Tasks.Task<_2017_05_24ULSAVentas.ServicioLocal.DevolverCadenaResponse> DevolverCadenaAsync() {
            _2017_05_24ULSAVentas.ServicioLocal.DevolverCadenaRequest inValue = new _2017_05_24ULSAVentas.ServicioLocal.DevolverCadenaRequest();
            inValue.Body = new _2017_05_24ULSAVentas.ServicioLocal.DevolverCadenaRequestBody();
            return ((_2017_05_24ULSAVentas.ServicioLocal.ServicioExamenSoap)(this)).DevolverCadenaAsync(inValue);
        }
        
        public double calcularTotal(int idPublicacion, int cantidad) {
            return base.Channel.calcularTotal(idPublicacion, cantidad);
        }
        
        public System.Threading.Tasks.Task<double> calcularTotalAsync(int idPublicacion, int cantidad) {
            return base.Channel.calcularTotalAsync(idPublicacion, cantidad);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _2017_05_24ULSAVentas.ServicioLocal.listaModeloResponse _2017_05_24ULSAVentas.ServicioLocal.ServicioExamenSoap.listaModelo(_2017_05_24ULSAVentas.ServicioLocal.listaModeloRequest request) {
            return base.Channel.listaModelo(request);
        }
        
        public _2017_05_24ULSAVentas.ServicioLocal.ArrayOfString listaModelo(string coincidencia) {
            _2017_05_24ULSAVentas.ServicioLocal.listaModeloRequest inValue = new _2017_05_24ULSAVentas.ServicioLocal.listaModeloRequest();
            inValue.Body = new _2017_05_24ULSAVentas.ServicioLocal.listaModeloRequestBody();
            inValue.Body.coincidencia = coincidencia;
            _2017_05_24ULSAVentas.ServicioLocal.listaModeloResponse retVal = ((_2017_05_24ULSAVentas.ServicioLocal.ServicioExamenSoap)(this)).listaModelo(inValue);
            return retVal.Body.listaModeloResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_2017_05_24ULSAVentas.ServicioLocal.listaModeloResponse> _2017_05_24ULSAVentas.ServicioLocal.ServicioExamenSoap.listaModeloAsync(_2017_05_24ULSAVentas.ServicioLocal.listaModeloRequest request) {
            return base.Channel.listaModeloAsync(request);
        }
        
        public System.Threading.Tasks.Task<_2017_05_24ULSAVentas.ServicioLocal.listaModeloResponse> listaModeloAsync(string coincidencia) {
            _2017_05_24ULSAVentas.ServicioLocal.listaModeloRequest inValue = new _2017_05_24ULSAVentas.ServicioLocal.listaModeloRequest();
            inValue.Body = new _2017_05_24ULSAVentas.ServicioLocal.listaModeloRequestBody();
            inValue.Body.coincidencia = coincidencia;
            return ((_2017_05_24ULSAVentas.ServicioLocal.ServicioExamenSoap)(this)).listaModeloAsync(inValue);
        }
    }
}
