<?xml version="1.0" encoding="utf-8"?><Database Name="UlsaVentas" Class="ULSAVentasDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=XPS-L502X\SQLEXPRESS;Initial Catalog=UlsaVentas;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="UlsaVentasConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[__MigrationHistory]" Member="__MigrationHistory">
    <Type Name="__MigrationHistory">
      <Column Name="MigrationId" Type="System.String" DbType="NVarChar(150) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ContextKey" Type="System.String" DbType="NVarChar(300) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Model" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ProductVersion" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Usuario" Member="Usuario">
    <Type Name="Usuario">
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="usuario" Member="usuario1" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="contrasena" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="idPersona" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Association Name="Usuario_Comentario" Member="Comentario" ThisKey="idUsuario" OtherKey="idUsuario" Type="Comentario" />
      <Association Name="Usuario_Compra" Member="Compra" ThisKey="idUsuario" OtherKey="idUsuario" Type="Compra" />
      <Association Name="Usuario_Favorito" Member="Favorito" ThisKey="idUsuario" OtherKey="idUsuario" Type="Favorito" />
      <Association Name="Usuario_Publicacion" Member="Publicacion" ThisKey="idUsuario" OtherKey="idUsuario" Type="Publicacion" />
      <Association Name="AspNetUsers_Usuario" Member="AspNetUsers" ThisKey="Id" OtherKey="Id" Type="AspNetUsers" IsForeignKey="true" />
      <Association Name="Persona_Usuario" Member="Persona" ThisKey="idPersona" OtherKey="idPersona" Type="Persona" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetRoles" Member="AspNetRoles">
    <Type Name="AspNetRoles">
      <Column Name="Id" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Association Name="AspNetRoles_AspNetUserRoles" Member="AspNetUserRoles" ThisKey="Id" OtherKey="RoleId" Type="AspNetUserRoles" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUserClaims" Member="AspNetUserClaims">
    <Type Name="AspNetUserClaims">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="ClaimType" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ClaimValue" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="AspNetUsers_AspNetUserClaims" Member="AspNetUsers" ThisKey="UserId" OtherKey="Id" Type="AspNetUsers" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUserLogins" Member="AspNetUserLogins">
    <Type Name="AspNetUserLogins">
      <Column Name="LoginProvider" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProviderKey" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="AspNetUsers_AspNetUserLogins" Member="AspNetUsers" ThisKey="UserId" OtherKey="Id" Type="AspNetUsers" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUserRoles" Member="AspNetUserRoles">
    <Type Name="AspNetUserRoles">
      <Column Name="UserId" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleId" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="AspNetRoles_AspNetUserRoles" Member="AspNetRoles" ThisKey="RoleId" OtherKey="Id" Type="AspNetRoles" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="AspNetUsers_AspNetUserRoles" Member="AspNetUsers" ThisKey="UserId" OtherKey="Id" Type="AspNetUsers" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUsers" Member="AspNetUsers">
    <Type Name="AspNetUsers">
      <Column Name="Id" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="EmailConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PasswordHash" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SecurityStamp" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumberConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TwoFactorEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LockoutEndDateUtc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LockoutEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AccessFailedCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Association Name="AspNetUsers_Usuario" Member="Usuario" ThisKey="Id" OtherKey="Id" Type="Usuario" />
      <Association Name="AspNetUsers_AspNetUserClaims" Member="AspNetUserClaims" ThisKey="Id" OtherKey="UserId" Type="AspNetUserClaims" />
      <Association Name="AspNetUsers_AspNetUserLogins" Member="AspNetUserLogins" ThisKey="Id" OtherKey="UserId" Type="AspNetUserLogins" />
      <Association Name="AspNetUsers_AspNetUserRoles" Member="AspNetUserRoles" ThisKey="Id" OtherKey="UserId" Type="AspNetUserRoles" />
    </Type>
  </Table>
  <Table Name="dbo.Comentario" Member="Comentario">
    <Type Name="Comentario">
      <Column Name="idComentario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idPublicacion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="comentario" Member="comentario1" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="fecha" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Usuario_Comentario" Member="Usuario" ThisKey="idUsuario" OtherKey="idUsuario" Type="Usuario" IsForeignKey="true" />
      <Association Name="Publicacion_Comentario" Member="Publicacion" ThisKey="idPublicacion" OtherKey="idPublicacion" Type="Publicacion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Compra" Member="Compra">
    <Type Name="Compra">
      <Column Name="idCompra" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idPublicacion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fecha" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="comentarioDeCompra" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="comentarioDeVenta" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="calificacionDeCompra" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="calificacionDeVenta" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Usuario_Compra" Member="Usuario" ThisKey="idUsuario" OtherKey="idUsuario" Type="Usuario" IsForeignKey="true" />
      <Association Name="Publicacion_Compra" Member="Publicacion" ThisKey="idPublicacion" OtherKey="idPublicacion" Type="Publicacion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Correo" Member="Correo">
    <Type Name="Correo">
      <Column Name="idCorreo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="direccionDeCorreo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="idPersona" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Persona_Correo" Member="Persona" ThisKey="idPersona" OtherKey="idPersona" Type="Persona" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Direccion" Member="Direccion">
    <Type Name="Direccion">
      <Column Name="idDireccion" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="calle" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="numeroExterior" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="numeroInterior" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="colonia" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="codigoPostal" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="estado" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="idPersona" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="longitud" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="latitud" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Association Name="Persona_Direccion" Member="Persona" ThisKey="idPersona" OtherKey="idPersona" Type="Persona" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Favorito" Member="Favorito">
    <Type Name="Favorito">
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idPublicacion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fechaDeAgregado" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="idFavorito" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="Usuario_Favorito" Member="Usuario" ThisKey="idUsuario" OtherKey="idUsuario" Type="Usuario" IsForeignKey="true" />
      <Association Name="Publicacion_Favorito" Member="Publicacion" ThisKey="idPublicacion" OtherKey="idPublicacion" Type="Publicacion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Persona" Member="Persona">
    <Type Name="Persona">
      <Column Name="idPersona" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombres" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="apellidoPaterno" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="apellidoMaterno" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="fechaDeNacimiento" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Persona_Usuario" Member="Usuario" ThisKey="idPersona" OtherKey="idPersona" Type="Usuario" />
      <Association Name="Persona_Correo" Member="Correo" ThisKey="idPersona" OtherKey="idPersona" Type="Correo" />
      <Association Name="Persona_Direccion" Member="Direccion" ThisKey="idPersona" OtherKey="idPersona" Type="Direccion" />
      <Association Name="Persona_TarjetaDeCredito" Member="TarjetaDeCredito" ThisKey="idPersona" OtherKey="idPersona" Type="TarjetaDeCredito" />
      <Association Name="Persona_Telefono" Member="Telefono" ThisKey="idPersona" OtherKey="idPersona" Type="Telefono" />
    </Type>
  </Table>
  <Table Name="dbo.Publicacion" Member="Publicacion">
    <Type Name="Publicacion">
      <Column Name="idPublicacion" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="titulo" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="precio" Type="System.Decimal" DbType="Decimal(9,2) NOT NULL" CanBeNull="false" />
      <Column Name="cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Publicacion_Comentario" Member="Comentario" ThisKey="idPublicacion" OtherKey="idPublicacion" Type="Comentario" />
      <Association Name="Publicacion_Compra" Member="Compra" ThisKey="idPublicacion" OtherKey="idPublicacion" Type="Compra" />
      <Association Name="Publicacion_Favorito" Member="Favorito" ThisKey="idPublicacion" OtherKey="idPublicacion" Type="Favorito" />
      <Association Name="Usuario_Publicacion" Member="Usuario" ThisKey="idUsuario" OtherKey="idUsuario" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TarjetaDeCredito" Member="TarjetaDeCredito">
    <Type Name="TarjetaDeCredito">
      <Column Name="idTarjeta" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="numeroDeTarjeta" Type="System.String" DbType="VarChar(22) NOT NULL" CanBeNull="false" />
      <Column Name="idPersona" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Persona_TarjetaDeCredito" Member="Persona" ThisKey="idPersona" OtherKey="idPersona" Type="Persona" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Telefono" Member="Telefono">
    <Type Name="Telefono">
      <Column Name="idTelefono" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="numero" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="idPersona" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Persona_Telefono" Member="Persona" ThisKey="idPersona" OtherKey="idPersona" Type="Persona" IsForeignKey="true" />
    </Type>
  </Table>
</Database>